language: nix
nix: 2.2.1
script: |
  # load the cache
  nix-env -iA cachix -f https://cachix.org/api/v1/install
  cachix use cross-armed

  # build an rpi0 sample image
  nix build -f . \
    -I nixpkgs=nixpkgs \
    -I machine=machines/raspberrypi-zerow \
    -I image=images/rpi0-otg-ether

  # build a beaglebone sample image
  nix build -f . \
    -I nixpkgs=nixpkgs \
    -I machine=machines/beaglebone \
    -I image=images/minimal
